Repository Clean18/NineTails_Project, pull requests merged in 2025-07, with the labels that each got.

#70 스킬 단축창 기능 추가
  Assets/CYH/CYH_SaveFiles/PlayerSaveFile
  Assets/CYH/CYH_Scripts/Skill/SkillLogic_1.cs
  Assets/CYH/CYH_Scripts/Skill/SkillLogic_2.cs
  Assets/CYH/CYH_Scripts/Skill/SkillLogic_3.cs
  Assets/CYH/CYH_Scripts/Skill/SkillLogic_4.cs
  Assets/CYH/CYH_Scripts/Skill/SkillLogic_5.cs
  Assets/CYH/CYH_Scripts/Skill/SkillLogic_6.cs
  Assets/LHJ/LHJ_Scripts/LHJ_UI/SkillButton.cs
  Assets/LHJ/LHJ_Scripts/LHJ_UI/SkillPopUp.cs
  Assets/LYH/08_Font/Mabinogi_Classic_TTF SDF.asset
  Assets/Resources/PopUp/SkillPopUp.prefab
  Assets/SJH/SJH_Scripts/PlayerController.cs
  Assets/SJH/SJH_Scripts/PlayerData.cs
  Assets/SJH/SJH_Scripts/PlayerModel.cs
  Assets/SJH/SJH_Scripts/PlayerSkill.cs
  Assets/Scenes/Stage1-1.unity
Labels: feature, fix:feature

#82 플레이어 코드 리팩토링 및 경고문 생성 기능 추가 등
  Assets/CYH/CYH_SO/Skill_6.asset
  Assets/CYH/CYH_SaveFiles/PlayerSaveFile
  Assets/CYH/CYH_Scripts/Data/SaveLoadManager.cs
  Assets/CYH/CYH_Scripts/Skill/SkillLogic_0_HitBox.cs
  Assets/CYH/CYH_Scripts/Skill/SkillLogic_1.cs
  Assets/CYH/CYH_Scripts/Skill/SkillLogic_2.cs
  Assets/CYH/CYH_Scripts/Skill/SkillLogic_3.cs
  Assets/CYH/CYH_Scripts/Skill/SkillLogic_4.cs
  Assets/CYH/CYH_Scripts/Skill/SkillLogic_5.cs
  Assets/CYH/CYH_Scripts/Skill/SkillLogic_6.cs
  Assets/LHJ/LHJ_Scripts/LHJ_UI/Main.cs
  Assets/LHJ/LHJ_Scripts/LHJ_UI/SkillPopUp.cs
  Assets/LHJ/LHJ_Scripts/LHJ_UI/StatUpPopUp.cs
  Assets/LHJ/LHJ_Scripts/LHJ_UI/UpgradePopUp.cs
  Assets/LHJ/LHJ_Scripts/Weapon/Upgrade.cs
  Assets/Prefabs/UIManager.prefab
  Assets/Resources/PopUp/SkillPopUp.prefab
  Assets/SJH/SJH_Prefab/DamageText.prefab
  Assets/SJH/SJH_Prefab/UI_Unable_Message.prefab
  Assets/SJH/SJH_Prefab/UI_Unable_Message.prefab.meta
  Assets/SJH/SJH_Prefab/WarningMessage.prefab
  Assets/SJH/SJH_Prefab/WarningMessage.prefab.meta
  Assets/SJH/SJH_Scripts/DamageText.cs
  Assets/SJH/SJH_Scripts/PlayerController.cs
  Assets/SJH/SJH_Scripts/PlayerData.cs
  Assets/SJH/SJH_Scripts/PlayerEquipment.cs
  Assets/SJH/SJH_Scripts/PlayerModel.cs
  Assets/SJH/SJH_Scripts/PlayerQuest.cs
  Assets/SJH/SJH_Scripts/PlayerSkill.cs
  Assets/SaveFiles.meta
  Assets/SaveFiles/PlayerSaveFile
  Assets/SaveFiles/PlayerSaveFile.meta
  Assets/Scenes/Stage1-1.unity
  Assets/Scripts/DataManager.cs
  Assets/Scripts/GameManager.cs
  Assets/Scripts/UIManager.cs
Labels: feature, fix:bug, fix:feature, refactor

#100 보스 1 수정 및 버그 해결
  Assets/KYH/KYH_MonsterMove/KYH_Prefebs/1StageBoss/Boss1Effect.cs
  Assets/KYH/KYH_MonsterMove/KYH_Prefebs/1StageBoss/Boss1Effect.cs.meta
  Assets/KYH/KYH_MonsterMove/KYH_Prefebs/1StageBoss/DropRock.prefab
  Assets/KYH/KYH_MonsterMove/KYH_Prefebs/1StageBoss/New_1StageBoss.prefab
  Assets/KYH/KYH_MonsterMove/KYH_Prefebs/1StageBoss/Tiger_Attack1_Effect1.prefab
  Assets/KYH/KYH_MonsterMove/KYH_Prefebs/1StageBoss/cone 1.prefab
  Assets/KYH/KYH_MonsterMove/KYH_scripts/BaseBossFSM.cs
  Assets/KYH/KYH_MonsterMove/KYH_scripts/FallingRock.cs
  Assets/KYH/KYH_MonsterMove/KYH_scripts/SpearGhostPrefebs.cs
  Assets/KYH/KYH_MonsterMove/KYH_scripts/Stage1BossFSM.cs
  Assets/KYH/KYH_MonsterMove/KYH_scripts/Stage2BossFSM.cs
  Assets/KYH/KYH_MonsterMove/KYH_scripts/Stage3BossFSM.cs
  Assets/SJH/SJH_Scripts/PlayerController.cs
  Assets/SaveFiles/PlayerSaveFile
  Assets/Scenes/Stage1-3_Battle.unity
  Assets/Scripts/GameManager.cs
Labels: fix:bug, fix:feature

#116 Fix : DialogScene 리소스 연동 & 1-1_Last 에서 스킵 불가능 기능 추가
  Assets/Animation/Monster/New_Range Monster.controller
  Assets/Animation/Monster/Ranged_Attack.anim
  Assets/CYH/CYH_Animation/AnimatorController/Skill_1_EffectAnimationController.controller
  Assets/CYH/CYH_Animation/AnimatorController/Skill_6_EffectAnimationController.controller
  Assets/KYH/KYH_MonsterMove/KYH_Prefebs/1StageBoss/Warning Circle.prefab
  Assets/KYH/KYH_MonsterMove/KYH_Prefebs/1StageBoss/WarningRects.prefab
  Assets/KYH/KYH_MonsterMove/KYH_Prefebs/2StageBoss/Giant_Swing_Bonk.anim
  Assets/KYH/KYH_MonsterMove/KYH_Prefebs/2StageBoss/WarningHammer.prefab
  Assets/KYH/KYH_MonsterMove/KYH_Prefebs/2StageBoss/WarningStomps.prefab
  Assets/KYH/KYH_MonsterMove/KYH_Prefebs/Normal Monster/BaseMonsterFSM.cs
  Assets/KYH/KYH_MonsterMove/KYH_Prefebs/Normal Monster/HeavyMonsterFSM.cs
  Assets/KYH/KYH_MonsterMove/KYH_Prefebs/Normal Monster/RangedMonsterFSM.cs
  Assets/KYH/Stage1-1(Copy).unity
  Assets/KYH/Stage1-1(Copy).unity.meta
  Assets/LYH/Scripts/DialogParser.cs
  Assets/Scenes/DialogScene.unity
  Assets/Scenes/Stage2-3_Battle.unity
Labels: feature, fix:feature
